version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root@pwd
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: app@pwd
    ports:
      - "3306:3306"
    volumes:
      - ./src/data/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - mysql_data:/var/lib/mysql
    networks:
      - app_net

  app:
    build: .
    ports:
      - "5000:3333"
    environment:
      - DB_HOST=root@pwd
      - DB_PORT=3306
      - DB_USER=appuser
      - DB_PASSWORD=app@pwd
      - DB_NAME=appdb
    depends_on:
      - mysql
    networks:
      - app_net

volumes:
  mysql_data:

networks:
  app_net:
    driver: bridge
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile.api
#     depends_on:
#       - sqlite_db
#     ports:
#       - "3636:3333"
#     volumes:
#       - sqlite_data:/app/src/data
#     networks:
#       - app_net

# volumes:
#   sqlite_data:

# networks:
#   app_net:
#     driver: bridge
